cakecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('cakes/', views.cakes_index, name='index'),
    path('cakes/<int:cake_id>/', views.cake_detail, name='detail'),
    path('cakes/create/', views.CakeCreate.as_view(), name='cakes_create'),
    path('cakes/<int:pk>/update/', views.CakeUpdate.as_view(), name='cakes_update'),
    path('cakes/<int:pk>/delete/', views.CakeDelete.as_view(), name='cakes_delete'),
    path('cakes/<int:cake_id>/add_combo/', views.add_combo, name='add_combo'),
    path('cakes/<int:cake_id>/add_photo/', views.add_photo, name='add_photo'),
    path('toppings/', views.ToppingList.as_view(), name='toppings_index'),
    path('toppings/<int:pk>/', views.ToppingDetail.as_view(), name = 'toppings_detail'),
    path('toppings/create/', views.ToppingCreate.as_view(), name="toppings_create"),
    path('toppings/<int:pk>/update/', views.ToppingUpdate.as_view(), name='toppings_update'),
    path('toppings/<int:pk>/delete/', views.ToppingDelete.as_view(), name="toppings_delete"),
    path('accounts/signup/', views.signup, name = 'signup'),
    path('cakes/<int:cake_id>/assoc_topping/<int:topping_id>/', views.assoc_topping, name='assoc_topping'),
    path('cakes/<int:cake_id>/unassoc_topping/<int:topping_id>/', views.unassoc_topping, name='unassoc_topping'),
    
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User


# Create your models here.

DRINKS = (
    ('T', 'Tea'),
    ('C', 'Coffee'),
    ('W', 'Water'),
)

class Topping(models.Model):
    name = models.CharField(max_length=20)
    portion = models.IntegerField()

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('toppings_detail', kwargs={'pk': self.id})

class Cake(models.Model):
    name = models.CharField(max_length=20)
    cal = models.IntegerField()
    description = models.TextField(max_length=100)
    toppings = models.ManyToManyField(Topping)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'cake_id': self.id})
    
    def combo_for_today(self):
        return self.combo_set.filter(date=date.today()).count() >= len(DRINKS)

class Combo(models.Model):
    date = models.DateField('Order date')
    drink = models.CharField(
        max_length=1,
        choices=DRINKS,
        default=DRINKS[2][0]
    )
    cake = models.ForeignKey(Cake, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_drink_display()} on {self.date}"


    class Meta:
        ordering = ['date']

class Photo(models.Model):
    url = models.CharField(max_length=200)
    cake = models.ForeignKey(Cake, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for cake_id: {self.cake_id} @{self.url}"

main_app/forms.py
from django.db import models
from django.forms import ModelForm, fields
from .models import Combo

class ComboForm(ModelForm):
    class Meta:
        model = Combo
        fields = ['date', 'drink']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
import uuid
import boto3
import sys
from .models import Cake, Topping, Photo
from .forms import ComboForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'annacakecollector'

# Create your views here.

from django.http import HttpResponse

from main_app import models


def home(request):
  return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def cakes_index(request):
  cakes = Cake.objects.filter(user=request.user)
  return render(request, 'cakes/index.html', {'cakes': cakes})

@login_required
def cake_detail(request, cake_id):
  cake = Cake.objects.get(id=cake_id)
  if cake.user == request.user:
    cake_no_toppings = Topping.objects.exclude(id__in = cake.toppings.all().values_list('id'))
    combo_form = ComboForm()
    return render(request, 'cakes/detail.html', { 
    'cake': cake, "combo_form": combo_form,
    'toppings': cake_no_toppings
     })
  redirect('/')

class CakeCreate(LoginRequiredMixin, CreateView):
  model = Cake
  fields = ['name', 'cal', 'description']
  def form_valid(self, form):
    form.instance.user = self.request.user  
    return super().form_valid(form)
  

class CakeUpdate(LoginRequiredMixin, UpdateView):
  model = Cake
  fields = '__all__'

class CakeDelete(LoginRequiredMixin, DeleteView):
  model = Cake
  success_url = '/cakes/'

@login_required
def add_combo(request, cake_id):
  form = ComboForm(request.POST)
  if form.is_valid():
    new_combo = form.save(commit=False)
    new_combo.cake_id = cake_id
    new_combo.save()
  return redirect('detail', cake_id=cake_id)

class ToppingList(LoginRequiredMixin, ListView):
    model = Topping

class ToppingDetail(LoginRequiredMixin, DetailView):
    model = Topping

class ToppingCreate(LoginRequiredMixin, CreateView):
    model = Topping
    fields = '__all__'

class ToppingUpdate(LoginRequiredMixin, UpdateView):
    model = Topping
    fields = ['portion']

class ToppingDelete(LoginRequiredMixin, DeleteView):
    model = Topping
    success_url = '/toppings/'

@login_required
def assoc_topping(request, cake_id, topping_id):
  Cake.objects.get(id=cake_id).toppings.add(topping_id)
  return redirect('detail', cake_id=cake_id)

@login_required
def unassoc_topping(request, cake_id, topping_id):
  Cake.objects.get(id=cake_id).toppings.remove(topping_id)
  return redirect('detail', cake_id=cake_id)

@login_required
def add_photo(request, cake_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            # we can assign to cat_id or cat (if you have a cat object)
            photo = Photo(url=url, cake_id=cake_id)
            photo.save()
        except Exception as e:
            print('An error occurred uploading file to S3', e)
    return redirect('detail', cake_id=cake_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}

<h1>About the Cake Collector</h1>
<hr />
<p>Hire the Cake Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Cake Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li><a href="/" class="left brand-logo">&nbsp;&nbsp;CakeCollector</a></li>
                </ul>
                <ul class="right">
                    {%if user.is_authenticated %}
                    <li>Hello, {{user.username | capfirst}}</li>
                    {% endif %}
                    <li><a href="{% url 'about' %}">About</a></li>
                    {%if user.is_authenticated %}
                    <li><a href="{% url 'toppings_create' %}">Add a Topping</a></li>
                    <li><a href="{% url 'toppings_index' %}">View All Toppings</a></li>
                    <li><a href="{% url 'cakes_create' %}">Add a Cake</a></li>
                    <li><a href="{% url 'index'%}">View All My Cakes</a></li>
                    <li><a href="{% url 'logout'%}">Log Out</a></li>
                    {% else %}
                    <li><a href="{% url 'signup' %}">Sign Up</a></li>
                    <li><a href="{% url 'login'%}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="page-footer">
        <div class="right">All Rights Reserved, &copy; 2021 Cake Collector &nbsp;</div>
    </footer>
</body>

</html>

main_app/templates/cakes/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Cake Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ cake.name }}</span>
                <p>Cal: {{ cake.cal }}</p>
                <p>Description: {{ cake.description }}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'cakes_update' cake.id %}">Edit</a>
                <a href="{% url 'cakes_delete' cake.id %}">Delete</a>
            </div>
        </div>
        {% for photo in cake.photo_set.all %}
    <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form action="{% url 'add_photo' cake.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <input type="submit" class="btn" value="Upload Photo">
  </form>
    </div>
    <div class="col s6">
        <form action="{% url 'add_combo' cake.id %}" method="post">
            {% csrf_token %}
            {{combo_form.as_p}}
            <input type="submit" class="btn" value="Add Combo">
        </form>
        <br>
        {% if cake.combo_for_today %}
        <div class="card-panel teal-text center-align">{{cake.name}} was taken with 3 or more times today</div>
        {% else %}
        <div class="card-panel red-text center-align">{{cake.name}} needs more combos today</div>
        {% endif %}
        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Combo</th>
                </tr>
            </thead>
            <tbody>
                {% for combo in cake.combo_set.all %}
                <tr>
                    <td>{{combo.date}}</td>
                    <td>{{combo.get_drink_display}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<hr>
<div class="row">
    <div class="col s6">
        <h3>{{ cake.name }}'s Toppings</h3>
        {% if cake.toppings.count %}
        {% for topping in cake.toppings.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    {{ topping.name }} - {{topping.portion}}
                </span>
            </div>
            <div class="card-action">
                <form action="{% url 'unassoc_topping' cake.id topping.id %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="btn">Remove</button>
                </form>
              </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>No Toppings :(</h5>
        {% endif %}
    </div>
    <div class="col s6">
        <h3>Available Toppings</h3>
        {% if toppings.count %}
          {% for topping in toppings.all %}
            <div class="card">
              <div class="card-content">
                <span class="card-title">
                {{ topping.name }} - {{topping.portion}}
                </span>
              </div>
              <div class="card-action">
                <form action="{% url 'assoc_topping' cake.id topping.id %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="btn">Add</button>
                </form>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <h5>{{cake.name}} Already Has All Toppings Available</h5>
        {% endif %}
      </div>
</div>

<script>
    var dateEl = document.getElementById('id_date');
    window.M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });

    var selectEl = document.getElementById('id_drink');
    window.M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/cakes/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Cake List</h1>

{% for cake in cakes %}
<div class="card">
  <a href="{% url 'detail' cake.id %}">
    <div class="card-content">
      <span class="card-title">{{ cake.name }}</span>
      <p>Cal: {{ cake.cal}}</p>
      <p>Description: {{ cake.description }}</p>
    </div>
  </a>
</div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/cake_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Cake</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' cake.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/cake_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Cake</h1>
{% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <ul>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_ul }}
      </ul>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/topping_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Topping</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'toppings_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/topping_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Topping Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ topping.name }}</span>
        <p>Portion: {{ topping.portion }}</p>
      </div>
      <div class="card-action">
          <a href="{% url 'toppings_update' topping.id %}"> Edit</a>
          <a href="{% url 'toppings_delete' topping.id %}"> Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/topping_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Topping</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/topping_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Topping List</h1>

{% for topping in topping_list %}
 <a href="{% url 'toppings_detail' topping.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ topping.name }}</span>
            <p>Portion: {{ topping.portion }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}